version: "3.8"

services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    expose:
      - "8080"  # Exposed to other containers but not to host
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
      SPRING_DATASOURCE_USERNAME: postgres.ukbozobkdgqtrfvmdwyx
      SPRING_DATASOURCE_PASSWORD: W4doJfSRlwz1m5Kf
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - backend

  game-service:
    build:
      context: ./game-service
    container_name: game-service
    expose:
      - "8080"
    depends_on:
      - auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
      SPRING_DATASOURCE_USERNAME: postgres.ukbozobkdgqtrfvmdwyx
      SPRING_DATASOURCE_PASSWORD: W4doJfSRlwz1m5Kf
      AUTH_SERVICE_URL: http://auth-service:8080/api/auth  # Note port change to 8080
    networks:
      - backend

  reverse-proxy:
    image: nginx:alpine
    ports:
      - "8080:80"  # Single external port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - game-service
    networks:
      - backend

networks:
  backend:
    driver: bridge