version: "3.8"

services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8080"  # Exposing the port to localhost
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
      SPRING_DATASOURCE_USERNAME: postgres.ukbozobkdgqtrfvmdwyx
      SPRING_DATASOURCE_PASSWORD: W4doJfSRlwz1m5Kf
      # Adding debugging option for service address
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - backend

  game-service:
    build:
      context: ./game-service
    container_name: game-service
    ports:
      - "8082:8080"
    depends_on:
      - auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
      SPRING_DATASOURCE_USERNAME: postgres.ukbozobkdgqtrfvmdwyx
      SPRING_DATASOURCE_PASSWORD: W4doJfSRlwz1m5Kf
      AUTH_SERVICE_URL: http://auth-service:8081/api/auth  # Using the internal Docker network
    networks:
      - backend

networks:
  backend:
    driver: bridge
