version: "3.8"

services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - backend

  game-service:
    build:
      context: ./game-service
    container_name: game-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/game_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      AUTH_SERVICE_URL: http://auth-service:8081/api/auth
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
